(function () {
  "use strict";

  document.addEventListener("DOMContentLoaded", function () {
    var session = RMSSession.getSession();
    if (!session) {
      window.location.href = "../index.html";
      return;
    }

    document.getElementById("print-receipt-btn").addEventListener("click", function () {
      window.print();
    });

    renderReceipt(session);
  });

  function renderReceipt(session) {
    var params = new URLSearchParams(window.location.search);
    var paymentId = params.get("id");
    var payment = RMSStore.getPaymentById(paymentId);
    var container = document.getElementById("receipt-container");
    var backLink = document.getElementById("receipt-back-link");

    if (session.role === "owner") {
      backLink.href = "owner/payment-history.html";
    } else {
      backLink.href = "tenant/payment-history.html";
    }

    if (!payment) {
      container.innerHTML = '<div class="empty-state"><p>Receipt not found.</p></div>';
      return;
    }

    if (session.role === "tenant") {
      var tenant = RMSStore.getTenantByLogin(session.username);
      if (!tenant || payment.tenantId !== tenant.id) {
        window.location.href = "tenant/payment-history.html";
        return;
      }
    }

    var tenantDetails = RMSStore.getTenantById(payment.tenantId);
    var property = RMSStore.getPropertyById(payment.propertyId);

    container.innerHTML =
      '<div class="receipt-header">' +
        "<h1>Rent Payment Receipt</h1>" +
        "<p>Rent Management System</p>" +
      "</div>" +
      '<div class="detail-list">' +
        detailRow("Receipt ID", payment.receiptId) +
        detailRow("Tenant Name", tenantDetails ? tenantDetails.name : "—") +
        detailRow("Property", property ? property.name : "—") +
        detailRow("Room Number", tenantDetails ? tenantDetails.roomNumber : "—") +
        detailRow("Payment Month", RMSUtils.getMonthLabel(payment.month)) +
        detailRow("Amount Paid", RMSUtils.formatCurrency(payment.amount)) +
        detailRow("Payment Date", RMSUtils.formatDate(payment.paymentDate)) +
        detailRow("Payment Method", payment.method) +
        detailRow("Status", payment.status) +
      "</div>" +
      '<div style="margin-top:1.5rem">' +
        "<p>This is a browser-printable demo receipt generated by the frontend prototype.</p>" +
      "</div>";
  }

  function detailRow(label, value) {
    return '<div class="detail-item"><span class="label">' + RMSUtils.escapeHtml(label) + '</span><span class="value">' + RMSUtils.escapeHtml(String(value || "—")) + "</span></div>";
  }
})();
